table Customer
	lineageTag: t-customer-0001

	/// Average proxy credit limit across customers (department/division cardholder groups) in the current filter context
	measure 'Average Credit Limit' = AVERAGE(Customer[CreditLimitProxy])
		formatString: $#,##0.00

	/// Proxy "customer" key (Department | Division) representing a cardholder cost-center group, since the source has no individual cardholder ID. One row per distinct group.
	column CustomerKey
		dataType: string
		sourceColumn: CustomerKey

	/// State agency / department for this customer group - used as the demographic-equivalent proxy dimension
	column DeptName
		dataType: string
		sourceColumn: DeptName

	/// Division within the department for this customer group
	column DivName
		dataType: string
		sourceColumn: DivName

	/// Total number of transactions made by this customer group - proxy for transaction frequency
	column TransactionCount
		dataType: int64
		formatString: #,##0
		summarizeBy: sum
		sourceColumn: TransactionCount

	/// Total dollar amount spent by this customer group across all transactions
	column TotalSpend
		dataType: decimal
		formatString: $#,##0.00
		summarizeBy: sum
		sourceColumn: TotalSpend

	/// Average dollar amount per transaction for this customer group
	column AvgTransactionAmount
		dataType: decimal
		formatString: $#,##0.00
		summarizeBy: average
		sourceColumn: AvgTransactionAmount

	/// Largest single transaction amount observed for this customer group - used to derive the credit limit proxy
	column MaxTransactionAmount
		dataType: decimal
		formatString: $#,##0.00
		summarizeBy: none
		isHidden
		sourceColumn: MaxTransactionAmount

	/// Proxy for credit limit: 3x the largest single transaction observed for this customer group. The source data has no real credit-limit field, so this approximates a reasonable spending ceiling from observed behavior.
	column CreditLimitProxy
		dataType: decimal
		formatString: $#,##0.00
		summarizeBy: average
		sourceColumn: CreditLimitProxy

	partition Customer = m
		mode: import
		source =
				let
					// Started from the already-cleaned Transactions query so both tables stay perfectly consistent
					Source = Transactions,

					// Normalized the case of DeptName/DivName/CustomerKey BEFORE grouping. The source data has a small
					// number of divisions whose casing is inconsistent (e.g. "PUBLIC DEFENDER" vs "Public Defender"
					// under department LEGAL). Table.Group below is case-SENSITIVE (M's default text comparer), so
					// without this step those rows would survive grouping as two separate "duplicate" groups whose
					// CustomerKey text differs only by case. Power BI's data model (VertiPaq/DAX) compares text
					// case-INSENSITIVELY, so it would then reject the two differently-cased CustomerKey values as a
					// duplicate on the "one" side of the Customer<->Transactions relationship, breaking refresh.
					// Upper-casing here (matching DeptName's existing 100%-uppercase convention in the source data)
					// collapses any such case-variant rows into a single true group before grouping ever runs.
					#"Normalized Case" = Table.TransformColumns(Source, {{"DeptName", Text.Upper, type text}, {"DivName", Text.Upper, type text}, {"CustomerKey", Text.Upper, type text}}),

					// Grouped every transaction row up to its cardholder-group "customer" proxy (Department + Division)
					#"Grouped By Customer" = Table.Group(#"Normalized Case", {"CustomerKey", "DeptName", "DivName"}, {{"TransactionCount", each Table.RowCount(_), Int64.Type}, {"TotalSpend", each List.Sum([TransactionAmount]), type number}, {"AvgTransactionAmount", each List.Average([TransactionAmount]), type number}, {"MaxTransactionAmount", each List.Max([TransactionAmount]), type number}}),

					// Derived a proxy credit limit as 3x the largest single transaction observed for the group, since the source has no real credit-limit field
					#"Added Credit Limit Proxy" = Table.AddColumn(#"Grouped By Customer", "CreditLimitProxy", each Number.Round([MaxTransactionAmount] * 3, 2), type number),

					// Final safety net: CustomerKey is the "one" side of a relationship, so refresh fails outright if it
					// is ever violated. Guarantees uniqueness even if future source data introduces another case or
					// whitespace variant that the normalization above doesn't anticipate.
					#"Distinct Customer Key" = Table.Distinct(#"Added Credit Limit Proxy", {"CustomerKey"})
				in
					#"Distinct Customer Key"
